/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';
export const THEME_CHANGE_PALETTE_TYPE = 'THEME_CHANGE_PALETTE_TYPE';
export const THEME_CHANGE_DIRECTION = 'THEME_CHANGE_DIRECTION';
